// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"iot/server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/scan",
				Handler: scanHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/devices",
				Handler: getDevicesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/device/:uuid",
				Handler: getDeviceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/device/:uuid/func/:func",
				Handler: callFuncHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
